
server:
    port: 8089

spring:
    application:
        name: vaccineapi
#    cloud:
#        consul:
#            host: 10.0.2.6
#            port: 8500
#            discovery:
#                health-check-interval: 15s
    #  配置数据源
    datasource:
        # 数据库连接池 HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://rm-2ze165d0nn3703islo.mysql.rds.aliyuncs.com:3306/vaccine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: vaccine
        password: ZgPBqTL^OAP
        hikari:
            # 池中维护的最小空闲连接数
            minimum-idle: 5
            # 池中最大连接数，包括闲置和使用中的连接
            maximum-pool-size: 15
            # 自动提交
            auto-commit: true
            # 连接允许在池中闲置的最长时间
            idle-timeout: 30000
            # 池中连接最长生命周期
            max-lifetime: 1800000
            # 等待来自池的连接的最大毫秒数
            connection-timeout: 30000
    ## redis 配置
    redis:
        database: 8
        host: 127.0.0.1
        password:
        port: 6379
        timeout: 5000
        jedis:
            pool:
                # 最大空闲数
                max-idle: 10
                # 最小空闲数
                min-idle: 5
                #最大连接数（负值表示没有限制）
                max-active: 20
                # 最大建立连接等待时间（负值表示没有限制）
                max-wait: -1

logging:
    level:
        org.springframework.cloud.gateway: trace
        org.springframework.http.server.reactive: debug
        org.springframework.web.reactive: debug
        reactor.ipc.netty: debug

mybatis-plus:
    global-config:
        db-config:
            update-strategy: not_empty
